# -*- coding: utf-8 -*-
"""numpy_pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g12H8Mxw15AbIPk_QPhDpI2hHSzUYWdb
"""

import numpy as np

# Creating an array
arr = np.array([1, 2, 3, 4, 5])

# Performing arithmetic operations
arr_squared = arr ** 2

# Broadcasting
arr_broadcast = arr + 10

# Linear algebra operations
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix_a, matrix_b)

print("Original Array:", arr)
print("Squared Array:", arr_squared)
print("Broadcasted Array:", arr_broadcast)
print("Matrix Product:\n", matrix_product)

import pandas as pd

# Creating a DataFrame from a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df = pd.DataFrame(data)

# Displaying the DataFrame
print("Original DataFrame:")
print(df)

# Filtering data
filtered_df = df[df['Age'] > 30]

# Displaying filtered data
print("\nFiltered DataFrame:")
print(filtered_df)