# -*- coding: utf-8 -*-
"""practice2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wifvCHvDezdIOwYHmjRAqg53B-2bSXXy
"""

a = int(input("enter number:"))
b = int(input("enter number"))
print(a+b)
print(a-b)
print(a*b)

n = int(input("enter your number"))
if n%2 != 0:
    print("Weird")
elif n%2==0 and n>1 and n<6:
    print("Not Weird")
elif n%2==0 and n>5 and n<21:
    print("Weird")
elif n%2==0 and n>20:
    print("Not Weird")