# -*- coding: utf-8 -*-
"""practice6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1neXOAGlG297UxZ1FBfOpXzW9906o44pJ
"""

class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def introduce(self):
        print("Hello, my name is", self.name, "and I am", self.age, "years old.")

# Creating objects of the class Person
person1 = Person("Alice", 30)
person2 = Person("Bob", 25)

person1.introduce()  # Output: Hello, my name is Alice and I am 30 years old.
person2.introduce()  # Output: Hello, my name is Bob and I am 25 years old.

# Creating objects of the class Person
person1 = Person("Alice", 30)
person2 = Person("Bob", 25)

# Accessing attributes
print(person1.name)  # Output: Alice
print(person2.age)   # Output: 25

# Calling methods
person1.introduce()  # Output: Hello, my name is Alice and I am 30 years old.
person2.introduce()  # Output: Hello, my name is Bob and I am 25 years old.

# recurssion
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

# Example usage:
print(factorial(5))  # Output: 120

# function
def greet(name):
    print("Hello, " + name + "!")
greet("Alice")  # Output: Hello, Alice!

# for loop
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)

for char in "hello":
    print(char)

for num in range(5):
    print(num)

person = {"name": "Alice", "age": 30, "city": "New York"}

for key, value in person.items():
    print(key + ":", value)