# -*- coding: utf-8 -*-
"""practice3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tU_dEEQA0ZG6p17zz9EmBCAzCCycHqJx
"""

n = int(input())
    for i in range(1,n+1):
        print(i,end='')

year = int(input("Enter a year: "))

if year % 4 == 0:
    if year % 100 == 0:
        if year % 400 == 0:
            print(year, "is a leap year")
        else:
            print(year, "is not a leap year")
    else:
        print(year, "is a leap year")
else:
    print(year, "is not a leap year")