# -*- coding: utf-8 -*-
"""practice1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xNdffDXsUdFFGWt1WlcKCzIH7Ebw0FLi
"""

string = 'Hello World'
iterObj = iter(string)

while True:
    try:
        char1 = next(iterObj)
        print(char1)
    except StopIteration:
        break

import json

# JSON String:
colors =  '["Red", "Yellow", "Green", "Blue"]'

# JSON string to python dictionary:
lst1 = json.loads(colors)
print(lst1)

import json

# python dictionary
lst1 = ['Red', 'Yellow', 'Green', 'Blue']

# Convert Python dict to JSON
jsonObj = json.dumps(lst1)
print(jsonObj)

import json

print(json.dumps(22))               #integer
print(json.dumps(6.022))            #float
print(json.dumps("Hello World"))    #string
print(json.dumps(True))             #True
print(json.dumps(False))            #False
print(json.dumps(None))

import calendar

print(calendar.month(2024, 3))