# -*- coding: utf-8 -*-
"""practice4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZBkktESoFWOpRp72MKlxfjxor3RMFgc4
"""

def is_leap(year):


      if year %4 == 0 and year %100 !=0:
        return True
      elif year %4 == 0:
        if year %100 ==0:
            if year %400 ==0:
                return True
            else:
                return False
        else:
            return False
      else:
        return False