# -*- coding: utf-8 -*-
"""swap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zsIW-W-vh6hJxLCVrXAVclce133YqRI0
"""

#swap case
def swap_case(s):
    return ''.join([c.upper() if c.islower() else c.lower() for c in s])

#if __name__ == '__main__':

# string split and join
def split_and_join(line):
    # write your code here
    line = line.split(" ")
    line = "-".join(line)
    return line
if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

# mutate
def mutate_string(string, position, character):
    lst = list(string)
    lst[position] = character
    string = "".join(lst)
    return string

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)